apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: cluster-banestes
spec:
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: '1'
          memory: 512Mi
    userOperator:
      resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: '1'
          memory: 512Mi
      secretPrefix: user-
  kafka:
    authorization:
      superUsers:
        - admin
      type: simple
    config:
      num.network.threads: 6
      transaction.state.log.replication.factor: 3
      num.io.threads: 16
      min.insync.replicas: 2
      transaction.state.log.min.isr: 2
      message.max.bytes: 512000
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      default.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        tls: true
        type: route
    logging:
      loggers:
        rootLogger.level: 'INFO, ERROR'
      type: inline
    metadataVersion: 4.0-IV3
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    version: 4.0.0