apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: cluster-banestes
  name: admin
spec:
  authentication:
    type: scram-sha-512
    

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: cobranca
  labels:
    strimzi.io/cluster: cluster-banestes
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operations:
          - Read
        host: "*"
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"