apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-dev

resources:
  - ../../base

patches:
  - path: patch-subscription.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: amq-streams
      namespace: kafka-ambiente
      version: v1alpha1
  
  - path: patch-operatorgroup.yaml
    target:
      kind: OperatorGroup
      name: kafka-ambiente
