apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: strimzi
  name: bridge-metrics
spec:
  namespaceSelector:
    matchNames:
      - kafka-dev
  podMetricsEndpoints:
    - path: /metrics
      port: rest-api
  selector:
    matchLabels:
      strimzi.io/kind: KafkaBridge
      
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: strimzi
  name: cluster-operator-metrics
spec:
  namespaceSelector:
    matchNames:
      - kafka-dev
  podMetricsEndpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: strimzi
  name: entity-operator-metrics
spec:
  namespaceSelector:
    matchNames:
      - kafka-dev
  podMetricsEndpoints:
    - path: /metrics
      port: healthcheck
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: strimzi
  name: kafka-resources-metrics
spec:
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
          replacement: $1
          separator: ;
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: kubernetes_pod_name
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node_name
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_pod_host_ip
          targetLabel: node_ip
  selector:
    matchExpressions:
      - key: strimzi.io/kind
        operator: In
        values:
          - Kafka
          - KafkaConnect
          - KafkaMirrorMaker
          - KafkaMirrorMaker2
